name: Run and Commit Changes Hourly

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Python Script
        run: python app.py

      - name: Check for Changes
        id: check_changes
        run: |
          git config --global user.name "hosnn"
          git config --global user.email "soghtmd@gmail.com"
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.check_changes.outputs.no_changes == 'false'
        run: |
          git commit -m "Auto-update: Changes from Python script"

      - name: Push Changes
        if: steps.check_changes.outputs.no_changes == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
